// <auto-generated />
namespace Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RiskIP_ClassAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RiskIP_ClassAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202002221703482_RiskIP_ClassAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
